### ISSUE TITLE
Avoid downloading DTD files

### ISSUE THREAD

**Issue by cdekker** [ramonwirsch/fopRenderer#3]
I would like to convert an HTML page to PDF using your plugin. However, I noticed that the transform process is quite slow. Via --debug I noticed that most time is spent waiting on HTTP connections, retrieving the DTD schemas for the input document.

The start of my input document looks like this:

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
```

Is there a way I can feed it the .dtd files locally so it wont try to download them over the heavily throttled w3.org connection?

**Comment by ramonwirsch** [comment]
Could you give me the configuration of my plugin?

Though I have never used it for that purpose, I do not believe the actual rendering should download anything, but the XML validation part might and I do not believe you need or want to validate html files, especially since xhtml is deprecated.

Looking at it, I could make the validation optional, if that is the cause of your problem, but I was unable to reproduce it yet.

**Comment by ramonwirsch** [comment]
Yep, the validation logic will attempt to use doctype definitions if nothing else is configured.
I released a new version (0.1.18) that adds the option "requiresValidation" to the render configuration.
If this is set to false, the validation should not be attempted anymore.

**Comment by cdekker** [comment]
To give a bit more context, I am currently converting a legacy project from Ant build.xml to Gradle. This project compiles a large static HTML page into a PDF.

Currently, it has all necessary files in our Git repo, including apache-fop.jar and dependencies, as well as  the .dtd files. I'd like to get these out of the repo and rely only on our source to be in Git.

**Comment by ramonwirsch** [comment]
Sorry, accidentally compiled partly for Java 10, version 0.1.20 now targets Java 8 again.

I have never used dtd files for validation and never verified my plugin to work with them, so there might be an additional error source.

But the plugin is primarily intended to validate against schemata that are local (in the git).
Using the schemaUri property you can also explicitly specify remote schemata, but my plugin does not cache them and also does not watch there contents for changes. Meaning: if it is possible that the remote schemata can change, then gradle might not notice and re-validate.

**Comment by cdekker** [comment]
Ok thanks. Can confirm that this is now working again on Java 8!

As this is a legacy project, I simply moved the necessary DTD files in with the source folder and referenced them dynamically like so:

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "dtd/xhtml1-strict.dtd">`

I need them, since without them it would not resolve `&copy;` and other special characters.

**Comment by ramonwirsch** [comment]
Ok,
just to explain: the xml validation and transformation done by my plugin are entirely different processes.

As far as i now the XSL transformation part in java does not care at all about that. And if you do not want my plugin to check whether the input files conform to the doctypes then you can just leave the schema part out of the configuration and disable validation.

Even if you want the plugin to validate, you should still configure these explicitly so that gradle knows about them and uses those files for up-to-date checks.
